version: '3.8'

services:
  blog:
    build: .
    ports:
      - "8456:8000"
    volumes:
      - ./posts:/app/posts
      - ./templates:/app/templates:ro
    env_file:
      - .env
    restart: unless-stopped
