name: Tests & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]

    - name: Run tests with coverage
      run: |
        chmod +x runtests.sh
        ./runtests.sh

    - name: Generate coverage badge
      run: |
        pip install genbadge[coverage]
        python -c "
        import json
        with open('coverage.json') as f:
            data = json.load(f)
            coverage = data['totals']['percent_covered_display']
        with open('coverage_badge.svg', 'wb') as f:
            from genbadge import Badge
            badge = Badge('coverage', f'{coverage}%', 
                         color='brightgreen' if float(coverage) >= 90 
                         else 'yellow' if float(coverage) >= 70 
                         else 'red')
            f.write(badge.svg())
        "

    - name: Update README with coverage badge
      run: |
        # Sichern der alten README
        cp README.md README.md.bak
        
        # Prüfen, ob bereits ein Coverage Badge existiert
        if grep -q "!\[Coverage\]" README.md; then
          # Ersetze existierendes Badge
          sed -i "s|!\[Coverage\]([^)]*)|![Coverage](./coverage_badge.svg)|" README.md
        else
          # Füge Badge am Anfang der Datei ein (nach dem ersten Titel)
          sed -i "0,/^# /!b;//a\\\\n![Coverage](./coverage_badge.svg)\\n" README.md
        fi

    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add coverage_badge.svg README.md
        git commit -m "Update coverage badge" || echo "No changes to commit"
        git push
