name: Tests & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]

    - name: Run tests with coverage
      run: |
        chmod +x runtests.sh
        ./runtests.sh

    - name: Update Coverage Badge
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      uses: we-cli/coverage-badge-action@main
